# ============================================================================
# Copyright (c) 2026 - W2Inc, All Rights Reserved.
# See README.md in the project root for license information.
# ============================================================================
# Running postgres directly via docker container due to:
# - Avoid Dynamic Bind mounts as some platforms don't support it (security).
# - Future Possibility to customize more things if need be.
# ============================================================================

FROM docker.io/library/postgres:17
COPY ./init /docker-entrypoint-initdb.d