/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the currently authenticated user.
         * @description When authenticated it's useful to know who you currently are logged in as.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDO"];
                        "application/json": components["schemas"]["UserDO"];
                        "text/json": components["schemas"]["UserDO"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/current/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the currently authenticated user.
         * @description When authenticated it's useful to know who you currently are logged in as.
         */
        get: {
            parameters: {
                query?: {
                    "filter[read]"?: boolean;
                    "filter[variant]"?: components["schemas"]["NotifiableVariant"];
                    "filter[not[variant]]"?: components["schemas"]["NotifiableVariant"];
                    /** @description The page number/index */
                    "page[index]"?: number | string;
                    /** @description The amount of results per page */
                    "page[size]"?: number | string;
                    /** @description The name of the property to use for sorting. */
                    "sort[by]"?: string;
                    /** @description The sort direction. */
                    "sort[order]"?: components["schemas"]["Order"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDO"];
                        "application/json": components["schemas"]["UserDO"];
                        "text/json": components["schemas"]["UserDO"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the currently authenticated user.
         * @description When authenticated it's useful to know who you currently are logged in as.
         */
        get: {
            parameters: {
                query?: {
                    "filter[read]"?: boolean;
                    "filter[variant]"?: components["schemas"]["NotifiableVariant"];
                    "filter[not[variant]]"?: components["schemas"]["NotifiableVariant"];
                    /** @description The page number/index */
                    "page[index]"?: number | string;
                    /** @description The amount of results per page */
                    "page[size]"?: number | string;
                    /** @description The name of the property to use for sorting. */
                    "sort[by]"?: string;
                    /** @description The sort direction. */
                    "sort[order]"?: components["schemas"]["Order"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NotificationDO"];
                        "application/json": components["schemas"]["NotificationDO"];
                        "text/json": components["schemas"]["NotificationDO"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NotifiableVariant: number;
        NotificationData: components["schemas"]["NotificationDataMessageDO"];
        NotificationDataMessageDO: {
            /** @enum {string} */
            type?: "Default";
            text: string;
            html: string;
        };
        NotificationDO: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            data?: components["schemas"]["NotificationData"];
            descriptor?: components["schemas"]["NotifiableVariant"];
            /** Format: date-time */
            readAt?: null | string;
            /** Format: uuid */
            resourceId?: null | string;
        };
        /** @enum {unknown} */
        Order: "Ascending" | "Descending";
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        UserDetailsDO: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            email: null | string;
            markdown: null | string;
            firstName: null | string;
            lastName: null | string;
            githubUrl: null | string;
            linkedinUrl: null | string;
            redditUrl: null | string;
            websiteUrl: null | string;
        };
        UserDO: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            login: string;
            displayName: null | string;
            avatarUrl: null | string;
            details: null | components["schemas"]["UserDetailsDO"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
